-- Create the projects table for your portfolio
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  problem_statement TEXT NOT NULL,
  tech_stack VARCHAR(500) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  live_url VARCHAR(500),
  github_url VARCHAR(500) NOT NULL,
  project_type VARCHAR(10) NOT NULL CHECK (project_type IN ('web', 'mobile')),
  order_index INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert sample projects (replace YOUR_USERNAME with your actual GitHub username)
INSERT INTO projects (name, problem_statement, tech_stack, image_url, live_url, github_url, project_type, order_index) VALUES
('E-Commerce Platform', 'A modern e-commerce platform with real-time inventory management and secure payment processing.', 'React, Node.js, MongoDB, Stripe', '/uploads/project1.jpg', 'https://example.com', 'https://github.com/YOUR_USERNAME/ecommerce-platform', 'web', 1),
('Task Management App', 'Collaborative task management application with real-time updates and team collaboration features.', 'Vue.js, Express, PostgreSQL, Socket.io', '/uploads/project2.jpg', 'https://example.com', 'https://github.com/YOUR_USERNAME/task-management-app', 'web', 2),
('Weather Dashboard', 'Interactive weather dashboard with detailed forecasts, maps, and severe weather alerts.', 'React, TypeScript, OpenWeather API, Chart.js', '/uploads/project3.jpg', 'https://example.com', 'https://github.com/YOUR_USERNAME/weather-dashboard', 'web', 3),
('Social Media Analytics', 'Comprehensive analytics platform for social media performance tracking and insights.', 'Angular, Python, Django, Redis', '/uploads/project4.jpg', 'https://example.com', 'https://github.com/YOUR_USERNAME/social-media-analytics', 'web', 4),
('Video Streaming Platform', 'Scalable video streaming service with adaptive bitrate and content recommendations.', 'Next.js, AWS, FFmpeg, WebRTC', '/uploads/project5.jpg', 'https://example.com', 'https://github.com/YOUR_USERNAME/video-streaming-platform', 'web', 5),
('Fitness Tracker', 'Mobile fitness tracking app with workout planning, progress monitoring, and social features.', 'React Native, Firebase, Redux, Node.js', '/uploads/project6.jpg', 'https://example.com', 'https://github.com/YOUR_USERNAME/fitness-tracker', 'mobile', 6),
('Food Delivery App', 'On-demand food delivery app with real-time tracking, restaurant listings, and payment integration.', 'Flutter, Django, PostgreSQL, Google Maps API', '/uploads/project7.jpg', 'https://example.com', 'https://github.com/YOUR_USERNAME/food-delivery-app', 'mobile', 7),
('Expense Manager', 'Personal finance management app with expense tracking, budget planning, and analytics.', 'React Native, Express, MongoDB, Chart.js', '/uploads/project8.jpg', 'https://example.com', 'https://github.com/YOUR_USERNAME/expense-manager', 'mobile', 8);

-- Create index for better performance
CREATE INDEX idx_projects_type ON projects(project_type);
CREATE INDEX idx_projects_order ON projects(order_index);
